### ISSUE TITLE
No Examples Branch per README

### ISSUE THREAD

**Issue by galenandrew** [sq1agency/react-express-starter#1]
The README references an `examples` branch for referencing…examples. There is no example branch present in the repo.

**Comment by mikemclaren** [comment]
Fair enough! I forgot about the examples! Will need to get around to those.

**Comment by mikemclaren** [comment]
There is now an `examples` branch, which contains a To-Do List example!

**Comment by galenandrew** [comment]
:metal: nice dude!!
